describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:8080/register')
    cy.get('#email').click()
    cy.get('#email').clear()
    cy.get('#username').click()
    cy.get('#email').type('joseameridac@gmail.com')
    cy.get('#username').clear()
    cy.get('#username').type('tono')
    cy.get('#password').click()
    cy.get('#password').clear()
    cy.get('#password').type('Contrasena')
    cy.get('#password').clear()
    cy.get('#password').type('Contrasena1')
    cy.get('#password').clear()
    cy.get('#password').type('Contrasena1!')
    cy.get('.auth-button').click()
    cy.get('a').click()
    cy.get('#username').click()
    cy.get('#username').clear()
    cy.get('#username').type('tono')
    cy.get('#password').click()
    cy.get('#password').clear()
    cy.get('#password').type('C')
    cy.get('#password').clear()
    cy.get('.auth-button').click()
    cy.get('#password').type('Contrasena1!{enter}')
    cy.get('[href="/calendar"]').click()
    cy.get(':nth-child(5) .expand-btn').click()
    cy.get(':nth-child(1) > .interval-label').click()
    cy.get('#appt-patient').click()
    cy.get('#appt-patient').clear()
    cy.get('#appt-patient').type('ju')
    cy.get('#appt-patient').click()
    cy.get('#appt-patient').clear()
    cy.get('#appt-patient').type('j')
    cy.get('#appt-patient').clear()
    cy.get('#appt-patient').type('ju')
    cy.get('.suggestion-name').click()
    cy.get('.btn-primary').click()
    cy.get('.appointment-item').should('be.visible')
  })
})
