describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:8080/register')

    cy.get('a').click()
    cy.get('#username').click()
    cy.get('#username').clear()
    cy.get('#username').type('tono')
    cy.get('#password').click()
    cy.get('#password').clear()
    cy.get('#password').type('E')
    cy.get('#password').clear()
    cy.get('#password').type('Example1')
    cy.get('#password').clear()
    cy.get('#password').type('Contrasena1!')
    cy.get('.auth-button').click()
    cy.get('input').click()
    cy.get('input').clear()
    cy.get('input').type('ma')
    cy.get('.suggestions-list :nth-child(2)').click()
    cy.get(':nth-child(1) > .consultation-reason').should('be.visible')
    cy.get(':nth-child(2) > .consultation-reason').should('be.visible')
    cy.get(':nth-child(3) .consultation-reason').should('be.visible')
    cy.get('.add-button').click()
    cy.get('.consultation-header h2').should('be.visible')
  })
})
